apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment

  labels:

    app: nginx

spec:

  replicas: 3

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: 971076122335.dkr.ecr.us-west-1.amazonaws.com/demo:dotnet-app-buildNumber

        ports:

        - containerPort: 80
