apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
    created_by: phani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      created_by: phani
  template:
    metadata:
      labels:
        app: sample
        created_by: phani
    spec:
      containers:
      - name: sample
        image: 971076122335.dkr.ecr.us-west-1.amazonaws.com/demo:demo-project-changebuildnumber
        ports:
        - containerPort: 80
